### ISSUE TITLE
Incompatible with latest October

### ISSUE THREAD

**Issue by frthjf** [TimFoerster/octobercms-async-queue#1]
Hi, the plugin seems incompatible with latest October, see https://github.com/octobercms/october/issues/4009

Can you update the Async driver to the latest version? 

```"barryvdh/laravel-async-queue": "0.7.*"```

**Comment by TimFoerster** [comment]
Bumped to the new version.
Please update the plugin.

**Comment by frthjf** [comment]
Thanks a lot!
